baseURL = 'https://collect.fn.pub'
languageCode = 'zh-hans'
defaultContentLanguage = 'zh'
title = 'Heaven Is'
theme = "hortensia"	
enableRobotsTXT = true
hasCJKLanguage = true
rssLimit = 10
copyright = "unlicense yet."
enableEmoji =  true
disableKinds = ["taxonomy"]
staticDir = ["static"]

[author]
	name = "Byte"

[markup.goldmark.renderer]
	unsafe = true

[markup.highlight]
        noclasses = false

[params]
	simpleCSSURL = "/hortensia.min.css"
	dateformNumTime = "2006-01-02 15:04 -0700"
	footerCopyright = '<a href="https://github.com/heterog" target="_blank" rel="noopener">M-x</a>'

[[menu.main]]
	name = "[->+<]"
	url = "/"
	weight = 1
[[menu.main]]
	name = "About"
	url = "about"
	weight = 2

[permalinks]
        posts = ':year/:filename'
